source 'https://rubygems.org'
gemspec
gem 'rspec', :require => 'spec'
gem 'cenit-collection-base'
gem 'cenit-client'
gem 'activesupport'
#Include Cenit Collection Gem dependency
#gem 'cenit-collection-[My Dependency]'

